version: '2'

services:
  rdbms:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - ./conf/mysql/:/etc/mysql/conf.d:Z
      - data-mariadb:/var/lib/mysql
    ports:
      - "$RDBMSPORT:3306"
  solr:
    image: solr:6.6
    volumes:
      - ./docker/solr/:/tmp/solr:Z
      - data-solr:/opt/solr
    entrypoint:
      - docker-entrypoint.sh
      - /tmp/solr/precreate
    ports:
      - "$SOLRPORT:8983"
  rais:
    image: uolibraries/rais
    environment:
      - RAIS_IIIFURL=$APP_URL:$HTTPPORT/images/iiif
      - RAIS_TILECACHELEN=250
    volumes:
      - ./docker/data/batches:/var/local/images:z
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/opt/openoni:z
      - ./docker/data:/opt/openoni/data:z
    ports:
      - "$HTTPPORT:80"
    depends_on:
      - rdbms
    links:
      - rdbms
      - solr
      - rais
    environment:
      - APACHE_LOG_LEVEL
      - APP_URL
      - HTTPPORT
volumes:
  data-mariadb: {}
  data-solr: {}
