version: '1'

services:
  mysql:
    image: mysql
    environment:
		- MYSQL_ROOT_PASSWORD=12345
		- MYSQL_DATABASE=openoni
		- MYSQL_USER=openoni
		- MYSQL_PASSWORD=openoni
    volumes:
		- datavolume:/var/lib/mysql
  solr:
    image: solr
    environment:
    volumes:
    ports:
  rais:
    image: uolibraries/rais
    environment:
    volumes:
    ports:
  openoni:
    image:
    environment:
    volumes:
    ports:
