version: '1'

services:
  mysql:
    image:
    environment:
    volumes:
    ports:
  solr:
    image:
    environment:
    volumes:
    ports:
  rais:
    image:
    environment:
    volumes:
    ports:
  openoni:
    image:
    environment:
    volumes:
    ports:
