version: '1'

services:
  mysql:
    image:
      mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD=123456
      MYSQL_DATABASE=openoni
      MYSQL_USER=openoni
      MYSQL_PASSWORD=openoni
    volumes:
      - openoni-dev-data-mysql:/var/lib/mysql
      - /$(pwd)/docker/mysql:/etc/mysql/conf.d:Z
  solr:
    image:
    environment:
    volumes:
  rais:
    image:
    environment:
    volumes:
  openoni:
    image:
    environment:
    volumes:
    ports:
      - "80"
    links:
      - mysql
      - solr
      - rais
